# Exercício 24

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


#### Utilize o dataset zoo_2.csv e execute o algoritmo utilizando o método holdout, reservando apenas 20% dos dados para teste.

In [9]:
data = pd.read_csv('documents/zoo_2.csv')
zoo = pd.DataFrame(data)

In [10]:
X = zoo.drop(columns='type')
y = zoo['type']

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [12]:
dtc = DecisionTreeClassifier() 

dtc.fit(X_train, y_train)

DecisionTreeClassifier()

In [13]:
y_test_pred = dtc.predict(X_test)
y_train_pred = dtc.predict(X_train)

#### Gere a matriz de confusão para os datasets de treino e teste.


In [14]:
print("Matriz de Confusão:")
print(confusion_matrix(y_test, y_test_pred))

Matriz de Confusão:
[[ 0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0]
 [ 0  0  2  0  0  0  0]
 [ 0  0  0  3  0  0  0]
 [ 0  0  0  0  1  0  0]
 [ 0  0  0  0  0 12  0]
 [ 1  0  0  0  0  0  0]]


#### Compute as métricas (precision, recall e f1-score) para os conjutos de treino e teste

In [15]:
classification_report

<function sklearn.metrics._classification.classification_report(y_true, y_pred, *, labels=None, target_names=None, sample_weight=None, digits=2, output_dict=False, zero_division='warn')>

In [18]:
classification_report(y_train, y_train_pred)

'              precision    recall  f1-score   support\n\n   amphibian       1.00      1.00      1.00         4\n        bird       1.00      1.00      1.00        18\n        fish       1.00      1.00      1.00        11\n      insect       1.00      1.00      1.00         5\ninvertebrate       1.00      1.00      1.00         9\n      mammal       1.00      1.00      1.00        29\n     reptile       1.00      1.00      1.00         4\n\n    accuracy                           1.00        80\n   macro avg       1.00      1.00      1.00        80\nweighted avg       1.00      1.00      1.00        80\n'

In [19]:
accuracy_score(y_train, y_train_pred)

1.0

#### Avalie e compare os resultados obtidos pelo dataset de treino e teste e identifique se houve overfitting, underfitting ou se o modelo induzido gerado é adequado para utilizar em dados não vistos.

In [27]:
print("Conjunto de Treino:")
print("Acurácia:", accuracy_score(y_train, y_train_pred))
print("Relatório de Classificação (Treino):")
print(classification_report(y_train, y_train_pred))
print("Matriz de Confusão (Treino):")
print(confusion_matrix(y_train, y_train_pred))

print("Conjunto de Teste:")
print("Acurácia:", accuracy_score(y_test, y_test_pred))
print("Relatório de Classificação (Teste):")
print(classification_report(y_test, y_test_pred))
print("Matriz de Confusão (Teste):")
print(confusion_matrix(y_test, y_test_pred))

Conjunto de Treino:
Acurácia: 1.0
Relatório de Classificação (Treino):
              precision    recall  f1-score   support

   amphibian       1.00      1.00      1.00         4
        bird       1.00      1.00      1.00        18
        fish       1.00      1.00      1.00        11
      insect       1.00      1.00      1.00         5
invertebrate       1.00      1.00      1.00         9
      mammal       1.00      1.00      1.00        29
     reptile       1.00      1.00      1.00         4

    accuracy                           1.00        80
   macro avg       1.00      1.00      1.00        80
weighted avg       1.00      1.00      1.00        80

Matriz de Confusão (Treino):
[[ 4  0  0  0  0  0  0]
 [ 0 18  0  0  0  0  0]
 [ 0  0 11  0  0  0  0]
 [ 0  0  0  5  0  0  0]
 [ 0  0  0  0  9  0  0]
 [ 0  0  0  0  0 29  0]
 [ 0  0  0  0  0  0  4]]
Conjunto de Teste:
Acurácia: 0.9523809523809523
Relatório de Classificação (Teste):
              precision    recall  f1-score   supp

C:\Users\Pedro Hörmann\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Pedro Hörmann\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Pedro Hörmann\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn

Overfitting: o modelo apresenta um desempenho excelente durante o treinamento, mas no conjunto de testes ele perde o mesmo desempenho, chegando até a ter resultados nulos em algumas situações.

#### Caso os resultados não estejam bons, altere os parâmetros do algoritmo para tentar melhorar o desempenho do modelo.

In [28]:
dtc = DecisionTreeClassifier(max_depth=5, random_state=42)

In [29]:
dtc

DecisionTreeClassifier(max_depth=5, random_state=42)

In [30]:
dtc.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=5, random_state=42)

In [31]:
print("Conjunto de Treino:")
print("Acurácia:", accuracy_score(y_train, y_train_pred))
print("Relatório de Classificação (Treino):")
print(classification_report(y_train, y_train_pred))
print("Matriz de Confusão (Treino):")
print(confusion_matrix(y_train, y_train_pred))

print("Conjunto de Teste:")
print("Acurácia:", accuracy_score(y_test, y_test_pred))
print("Relatório de Classificação (Teste):")
print(classification_report(y_test, y_test_pred))
print("Matriz de Confusão (Teste):")
print(confusion_matrix(y_test, y_test_pred))

Conjunto de Treino:
Acurácia: 1.0
Relatório de Classificação (Treino):
              precision    recall  f1-score   support

   amphibian       1.00      1.00      1.00         4
        bird       1.00      1.00      1.00        18
        fish       1.00      1.00      1.00        11
      insect       1.00      1.00      1.00         5
invertebrate       1.00      1.00      1.00         9
      mammal       1.00      1.00      1.00        29
     reptile       1.00      1.00      1.00         4

    accuracy                           1.00        80
   macro avg       1.00      1.00      1.00        80
weighted avg       1.00      1.00      1.00        80

Matriz de Confusão (Treino):
[[ 4  0  0  0  0  0  0]
 [ 0 18  0  0  0  0  0]
 [ 0  0 11  0  0  0  0]
 [ 0  0  0  5  0  0  0]
 [ 0  0  0  0  9  0  0]
 [ 0  0  0  0  0 29  0]
 [ 0  0  0  0  0  0  4]]
Conjunto de Teste:
Acurácia: 0.9523809523809523
Relatório de Classificação (Teste):
              precision    recall  f1-score   supp

C:\Users\Pedro Hörmann\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Pedro Hörmann\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Pedro Hörmann\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn

Houve alteração nos resultados obtidos, mas o desempenho no conjunto de teste não corresponde aos resultados alcançados nos dados de treino.